### PR TITLE
Simplify run training

### LINKED ISSUE #82: Assorted deletions/simplicatications
- [x] unused variables, e.g. local_iter_num, is current eval best so far, etc.
- [x] config presets within script
- [x] dataclass-dereived script arguments
- [x] eval callbacks -> straightforward inline functions in checkpoint logic
- [x] model_config should be a dict in gigaconfig reflecting huggingface model config jsons

### LINKED ISSUE #90: flatten + simplify training script arguments

### PR DESCRIPTION
**Pull request by jaidhyani**
This sits on top of the train_rework PRs; only the commits from c6fe08c ("[Remove unused imports in run_training.py](https://github.com/delphi-suite/delphi/commit/c6fe08c4321975b0dba9dd1143f2e13ed96f0720)") are really part of this PR. Everything important (before code review) should be here: https://github.com/delphi-suite/delphi/pull/101/commits/53ec2721443de1b5829952b68665310f5f9e8d64

### CODE REVIEW

**Comment by jettjaniak** [comment]
I think we should always rebase instead of merge and point PRs to the actual target branch. This one needs to be rebased now on top of main, but there are some conflicts I don't know what to do about

**Review by jettjaniak — CHANGES_REQUESTED** [review]
rebase

**Comment by jaidhyani** [comment]
> I think we should always rebase instead of merge and point PRs to the actual target branch. This one needs to be rebased now on top of main, but there are some conflicts I don't know what to do about

The tension here is with keeping PRs from getting huge while responding to code review. So you run into issues when you:

1. Make a bunch of diffs
2. Make PR-1 from those diffs
3. Continue working on more diffs on top of PR-1 (but not part of PR-1 because that would lead to the PR getting way too big and unwieldy and unfocused and hard to review)
4. Make a new PR with the diffs that have accumulated on top of PR-1
5. Get feedback on PR-1 and make updates to PR-1

At this point, rebasing PR-2 will require resolving conflicts for every diff that's been potentially touched by the code review diffs on PR-1, and this typically ends up being a huge and pointless waste of time, essentially resolving the same conflicts over and over again. Rebasing and fast-forwarding is great when you can do it, but this kind of situation is the exact reason why it's sometimes preferable to do a single merge and deal with the conflicts in one go.

**Comment by jettjaniak** [comment]
I agree with some things you're saying, I just think this is all solvable. Would love to discuss at our next meeting. In the meantime:

I did `git rebase -i --onto main COMMIT` where `COMMIT` is one commit before
> https://github.com/delphi-suite/delphi/commit/c6fe08c4321975b0dba9dd1143f2e13ed96f0720 ("[Remove unused imports in run_training.py](https://github.com/delphi-suite/delphi/commit/c6fe08c4321975b0dba9dd1143f2e13ed96f0720)")

I used the -i option just to drop the last commit that is a merge of main

The resulting branch is here #104, LMK if this looks good

**Comment by jaidhyani** [comment]
Replaced by #104

**Pull request closed without merging**
