### PR TITLE
Add llama2c setup instructions

### PR DESCRIPTION
**Pull request by jaidhyani**

### CODE REVIEW

**Comment by jettjaniak** [comment]
this will be required, so should go on top of setup instructions
like "1. clone the repo". btw, there is a single clone command that can get submodules

**Comment by jettjaniak** [comment]
we may have a submodule for mamba as well, not sure yet

**Review by jettjaniak — APPROVED** [review]
conditionally approved, see coment

**Comment by jaidhyani** [comment]
@jettjaniak Rad, incorporated changes

**Pull request merged**
